# ============================================================
# VALUES AMBIENTE DEV
# Overrides sobre values.yaml base
# ============================================================

backend:
  replicaCount: 1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "300m"
      memory: "384Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 2
  db:
    password: "dev-password-123"

frontend:
  image:
    tag: "c5f8314"
  replicaCount: 1
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"

postgresql:
  auth:
    password: "dev-password-123"
  primary:
    persistence:
      size: 1Gi

ingress:
  host: dev.174.138.124.207.nip.io
