apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pedido-app-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: pedido-app
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    # IMPORTANTE: reemplazar con la URL real del repo
    repoURL: https://github.com/TU_USUARIO/pedido-app
    targetRevision: HEAD
    path: charts/pedido-app
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: pedido-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
